#!/usr/bin/env python3
"""Generate or refresh AGENTS.md at the project root.

AGENTS.md is the cross-tool role contract for AI agents working in this
repository (consumed by Cursor, Aider, Codex, and Claude Code). It states:
  - which roles operate in which phase, with what tools
  - which hard constraints are gating
  - what the failure protocol is

The file content is bracketed by BEGIN/END markers so users can hand-edit
freely outside the markers without conflict. We only rewrite what's between
the markers.

Invoked from:
  - engineering_init.py — at end of init, to seed initial AGENTS.md
  - engineering_advance.py — after a successful phase transition, to refresh
  - manually — `python3 engineering_agents.py --refresh`
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from engineering_lib import (
    PHASES,
    load_lifecycle,
    project_root_arg,
    require_engineering,
    utc_now,
)

BEGIN_MARKER = "<!-- BEGIN harness-engineering generated -->"
END_MARKER = "<!-- END harness-engineering generated -->"

# Role -> phase mapping. The brief files in resources/briefs/ are the long
# form; this is the project-level summary.
ROLE_TABLE = [
    # (role, phase, tools)
    ("Discoverer",  "discovery",      "Read, Grep, Glob, AskUser"),
    ("Designer",    "design",         "Read, Edit, /change-spec"),
    ("Architect",   "architecture",   "Read, Edit (adrs/)"),
    ("Implementer", "implementation", "Read, Edit, Bash, /tdd-plan, /completion-verify"),
    ("Tester",      "test",           "Read, Bash, Agent, /security-review"),
    ("Releaser",    "release",        "Bash (git), Read"),
    ("Operator",    "ops",            "Read, Edit, Bash"),
]


def render_block(lifecycle: dict) -> str:
    """Build the markdown content that goes between the markers."""
    project = lifecycle.get("project", "this project")
    goal = lifecycle.get("goal", "(goal not set)")
    mode = lifecycle.get("mode", "standard")
    current_phase = lifecycle.get("current_phase", "discovery")
    risk_gates = lifecycle.get("risk_gates") or []
    skipped = [p for p in PHASES if lifecycle.get("active_units", {}).get(p) is None
               and p != current_phase] if mode == "minimal" else []

    lines: list[str] = []
    lines.append(f"<!-- generated by harness-engineering on {utc_now()} -->")
    lines.append(f"<!-- project: {project} -->")
    lines.append(f"<!-- mode: {mode}, current_phase: {current_phase} -->")
    lines.append("")
    lines.append("# AGENTS.md")
    lines.append("")
    lines.append(
        f"This project uses `harness-engineering` for AI-driven SDLC. "
        f"AI agents working here MUST follow this contract. The full per-phase "
        f"protocol lives at `.engineering/lifecycle.json` and the briefs in "
        f"`resources/briefs/*.md` of the harness-engineering skill."
    )
    lines.append("")
    lines.append(f"**Goal:** {goal}")
    lines.append(f"**Mode:** {mode}")
    lines.append(f"**Current phase:** {current_phase}")
    lines.append("")
    lines.append("## Roles")
    lines.append("")
    lines.append("| Role         | Active in phase   | Tools / discipline skills |")
    lines.append("| ------------ | ----------------- | ------------------------- |")
    for role, phase, tools in ROLE_TABLE:
        marker = " ←" if phase == current_phase else ""
        lines.append(f"| {role:<12} | {phase:<17} | {tools}{marker} |")
    lines.append("")
    lines.append(
        "Only one role is active at a time, determined by "
        "`.engineering/lifecycle.json` -> `current_phase`. The active row above "
        "is marked with ←. Out-of-phase work (e.g., editing design specs while "
        "in implementation) requires explicit revise via `engineering_revise.py`."
    )
    lines.append("")
    lines.append("## Hard Constraints")
    lines.append("")
    if risk_gates:
        lines.append("Risk gates that require explicit human confirmation (`--confirm`):")
        lines.append("")
        for gate in risk_gates:
            lines.append(f"- `{gate}`")
        lines.append("")
    else:
        lines.append("No risk gates configured — auto-drive proceeds without pausing.")
        lines.append("")
    lines.append(
        "All declared `verification_commands` and the campaign `test_command` "
        "must pass before advance accepts a phase as complete. Live execution "
        "happens in `engineering_advance.py` and (when the harness-discipline "
        "skill is installed) defers to `/completion-verify` for the canonical "
        "verdict."
    )
    lines.append("")
    lines.append("## Failure Protocol")
    lines.append("")
    lines.append(
        "1. If you cannot proceed (missing context, conflicting state, "
        "unresolvable ambiguity), write a clear blocker note in the active "
        "phase artifact and STOP. Do NOT silently switch phases or roles."
    )
    lines.append(
        "2. For autodrive runs (when `.harness/autodrive.json` is enabled), call "
        "`harness_autodrive.py --fail --reason \"<short reason>\"` to break the "
        "chain. AskUserQuestion is forbidden in autodrive."
    )
    lines.append(
        "3. After 3 failed self-test retries on the same feature, the harness "
        "automatically blocks the feature. Do not work around the block — it is "
        "a deliberate signal to re-evaluate."
    )
    lines.append("")
    if skipped:
        lines.append("## Skipped phases")
        lines.append("")
        lines.append(", ".join(f"`{p}`" for p in skipped))
        lines.append("")
    lines.append("## Detail")
    lines.append("")
    lines.append("- Lifecycle state: `.engineering/lifecycle.json`")
    lines.append("- Phase briefs: harness-engineering skill at `resources/briefs/<phase>.md`")
    lines.append("- Capability matrix: `harness-engineering/docs/dedup-matrix.md`")
    lines.append("- ID conventions: `harness-engineering/docs/id-conventions.md`")
    return "\n".join(lines)


def merge_with_existing(existing: str, generated: str) -> str:
    """Replace content between markers, preserving anything outside.

    If neither marker is present, the file becomes generated content
    surrounded by markers. If only one marker is present, treat as malformed
    and overwrite (preserving anything before BEGIN if BEGIN exists).
    """
    block = f"{BEGIN_MARKER}\n{generated}\n{END_MARKER}"
    if not existing:
        return block + "\n"

    has_begin = BEGIN_MARKER in existing
    has_end = END_MARKER in existing
    if has_begin and has_end:
        before = existing.split(BEGIN_MARKER, 1)[0]
        after = existing.split(END_MARKER, 1)[1]
        return f"{before}{block}{after}"
    if has_begin and not has_end:
        before = existing.split(BEGIN_MARKER, 1)[0]
        return f"{before}{block}\n"
    # No markers: prepend our block, keep user content below
    return f"{block}\n\n{existing}"


def emit_agents_md(project_root: Path, *, force: bool = False) -> Path | None:
    """Generate or refresh AGENTS.md at project_root. Returns the path written, or None."""
    require_engineering(project_root)
    lifecycle = load_lifecycle(project_root)
    target = project_root / "AGENTS.md"
    generated = render_block(lifecycle)
    existing = target.read_text(encoding="utf-8") if target.exists() else ""
    new_text = merge_with_existing(existing, generated)
    if not force and existing == new_text:
        return None
    target.write_text(new_text, encoding="utf-8")
    return target


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--project-root", default=".")
    p.add_argument("--refresh", action="store_true",
                   help="Always rewrite, even if content matches.")
    args = p.parse_args()
    root = project_root_arg(args.project_root)
    written = emit_agents_md(root, force=args.refresh)
    if written:
        print(f"WROTE {written}")
    else:
        print("AGENTS.md unchanged")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
